export default [
    {
        "DT_RowId": "1",
        "tag_name": "Chicago Bulls",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "2",
        "tag_name": "Liverpool",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "3",
        "tag_name": "LeBron James",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "4",
        "tag_name": "Novak Djoković",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "5",
        "tag_name": "Lionel Messi",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "6",
        "tag_name": "Premier league",
        "tag_type": "Takmičenje",
        "my_feed": "yes",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "7",
        "tag_name": "Golden State Warriors",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "8",
        "tag_name": "Tottenham",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "9",
        "tag_name": "Kevin Durant",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "10",
        "tag_name": "Rafael Nadal",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "11",
        "tag_name": "Harry Kane",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "12",
        "tag_name": "Napoli",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "13",
        "tag_name": "Boston Celtics",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "14",
        "tag_name": "Barcelona",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "15",
        "tag_name": "Stephen Curry",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "16",
        "tag_name": "Roger Federer",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "17",
        "tag_name": "Olivier Giroud",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "18",
        "tag_name": "Manchester United",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "no",
    }, {
        "DT_RowId": "19",
        "tag_name": "San Antonio Spurs",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "20",
        "tag_name": "Manchester City",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "21",
        "tag_name": "Russell Westbrook",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "22",
        "tag_name": "Alexander Zverev",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "23",
        "tag_name": "Cristiano Ronaldo",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "24",
        "tag_name": "Euroleague",
        "tag_type": "Takmičenje",
        "my_feed": "yes",
        "my_favourites": "no",
    }, {
        "DT_RowId": "25",
        "tag_name": "Washington Wizards",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "26",
        "tag_name": "Bayern Munich",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "27",
        "tag_name": "Kyrie Irving",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "28",
        "tag_name": "Juan Martin del Potro",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "29",
        "tag_name": "Romelu Lukaku",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "30",
        "tag_name": "Champions League",
        "tag_type": "Takmičenje",
        "my_feed": "yes",
        "my_favourites": "no",
    }, {
        "DT_RowId": "31",
        "tag_name": "Toronto Raptors",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "32",
        "tag_name": "Roma",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "33",
        "tag_name": "Giannis Antetokounmpo",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "34",
        "tag_name": "John Isner",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "35",
        "tag_name": "Robert Lewandowski",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "36",
        "tag_name": "World Cup",
        "tag_type": "Takmičenje",
        "my_feed": "yes",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "37",
        "tag_name": "Los Angeles Lakers",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "38",
        "tag_name": "PSG",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "39",
        "tag_name": "DeMarcus Cousins",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "40",
        "tag_name": "Tomas Berdych",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "41",
        "tag_name": "Edinson Cavani",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "42",
        "tag_name": "Monaco",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "43",
        "tag_name": "Phoenix Suns",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "44",
        "tag_name": "Juventus",
        "tag_type": "Fudbalski klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "45",
        "tag_name": "Blake Griffin",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "46",
        "tag_name": "Kei Nishikori",
        "tag_type": "Teniser",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "47",
        "tag_name": "Eden Hazard",
        "tag_type": "Fudbaler",
        "my_feed": "no",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "48",
        "tag_name": "ATP",
        "tag_type": "Takmičenje",
        "my_feed": "yes",
        "my_favourites": "no",
    },
    {
        "DT_RowId": "49",
        "tag_name": "Denver Nuggets",
        "tag_type": "Košarkaški klub",
        "my_feed": "yes",
        "my_favourites": "yes",
    },
    {
        "DT_RowId": "50",
        "tag_name": "Nikola Jokić",
        "tag_type": "Košarkaš",
        "my_feed": "no",
        "my_favourites": "no",
    },
    
]